### ISSUE TITLE
Exception while describing TAP service with security methods

### ISSUE THREAD

**Issue by cbanek** [pyvirtobs/pyvo#113]
Here's what I'm trying to run:
```
import pyvo

service = pyvo.dal.TAPService('https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/tap')
service.describe()
```

Here's the callstack:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    service.describe()
  File "/home/cbanek/pyvo/pyvo/dal/tap.py", line 324, in describe
    self.capabilities
  File "/home/cbanek/pyvo-env/lib/python3.6/site-packages/astropy/utils/decorators.py", line 744, in __get__
    val = self.fget(obj)
  File "/home/cbanek/pyvo/pyvo/dal/vosi.py", line 91, in capabilities
    return vosi.parse_capabilities(self._capabilities().read)
  File "/home/cbanek/pyvo/pyvo/io/vosi/endpoint.py", line 120, in parse_capabilities
    config=config, pos=(1, 1)).parse(iterator, config)
  File "/home/cbanek/pyvo/pyvo/io/vosi/endpoint.py", line 333, in parse
    super(CapabilitiesFile, self).parse(iterator, config)
  File "/home/cbanek/pyvo/pyvo/utils/xml/elements.py", line 288, in parse
    iterator, tag, data, config, pos)
  File "/home/cbanek/pyvo/pyvo/io/vosi/endpoint.py", line 320, in capabilities
    capability.parse(iterator, config)
  File "/home/cbanek/pyvo/pyvo/utils/xml/elements.py", line 288, in parse
    iterator, tag, data, config, pos)
  File "/home/cbanek/pyvo/pyvo/utils/xml/elements.py", line 202, in add_complexcontent
    element.parse(iterator, config)
  File "/home/cbanek/pyvo/pyvo/io/vosi/vodataservice.py", line 287, in parse
    super(ParamHTTP, self).parse(iterator, config)
  File "/home/cbanek/pyvo/pyvo/utils/xml/elements.py", line 288, in parse
    iterator, tag, data, config, pos)
  File "/home/cbanek/pyvo/pyvo/utils/xml/elements.py", line 230, in add_simplecontent
    getattr(self, attr_name).append(data)
  File "/home/cbanek/pyvo-env/lib/python3.6/site-packages/astropy/utils/collections.py", line 47, in append
    self._assert(x)
  File "/home/cbanek/pyvo-env/lib/python3.6/site-packages/astropy/utils/collections.py", line 31, in _assert
    "type '{}'".format(self._types))
TypeError: homogeneous list must contain only objects of type '<class 'pyvo.io.vosi.voresource.SecurityMethod'>'
```

Note this doesn't happen on some other TAP services, that don't have security methods set:

http://tapvizier.u-strasbg.fr/TAPVizieR/tap/

**Comment by cbanek** [comment]
I'm trying to debug this one, but this parser seems to have a pretty steep learning curve. :smile:

**Comment by funbaker** [comment]
Merged.
